# Generated by Django 3.1.7 on 2021-05-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210503_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='isSubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
