# Generated by Django 3.1.7 on 2021-05-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210508_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unregistered_subscribers',
            new_name='Unregistered_subscriber',
        ),
    ]
